"""empty message

Revision ID: e3a07512b73f
Revises: 105b6435def0
Create Date: 2019-05-16 23:02:48.181417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a07512b73f'
down_revision = '105b6435def0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'date')
    # ### end Alembic commands ###
