"""empty message

Revision ID: f292edbc5537
Revises: a754112f9824
Create Date: 2019-05-15 16:46:01.291000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f292edbc5537'
down_revision = 'a754112f9824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_participants_first_name'), 'participants', ['first_name'], unique=False)
    op.create_index(op.f('ix_participants_last_name'), 'participants', ['last_name'], unique=False)
    op.create_index(op.f('ix_participants_username'), 'participants', ['username'], unique=True)
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop')
    )
    op.create_table('rooms',
    sa.Column('room_no', sa.String(length=3), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('workshop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workshop'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('room_no')
    )
    op.drop_index('ix_employees_email', table_name='employees')
    op.drop_index('ix_employees_first_name', table_name='employees')
    op.drop_index('ix_employees_last_name', table_name='employees')
    op.drop_index('ix_employees_username', table_name='employees')
    op.drop_table('employees')
    op.drop_index('name', table_name='departments')
    op.drop_table('departments')
    op.drop_index('name', table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_index('name', 'roles', ['name'], unique=True)
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_index('name', 'departments', ['name'], unique=True)
    op.create_table('employees',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], [u'departments.id'], name=u'employees_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'employees_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_index('ix_employees_username', 'employees', ['username'], unique=True)
    op.create_index('ix_employees_last_name', 'employees', ['last_name'], unique=False)
    op.create_index('ix_employees_first_name', 'employees', ['first_name'], unique=False)
    op.create_index('ix_employees_email', 'employees', ['email'], unique=True)
    op.drop_table('rooms')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_participants_username'), table_name='participants')
    op.drop_index(op.f('ix_participants_last_name'), table_name='participants')
    op.drop_index(op.f('ix_participants_first_name'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
